# ---------------------------------------------  启动端口 ------------------------------------------------------- #
server:
  port: 8080

spring:
# ---------------------------------------------  数据库配置(默认使用mysql：8.0+) -----------------------------------#
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_manager?characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

# ---------------------------------------------  配置 JPA ------------------------------------------------------- #
  jpa:
    hibernate:
# ---------------------------------------------  更新策略 ------------------------------------------------------- #
      ddl-auto: update
# ---------------------------------------------  打印SQL ------------------------------------------------------- #
    show-sql: true
# ---------------------------------------------  自动生成表结构 ------------------------------------------------- #
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 2MB
# --------------------------------------------- 配置mybatis ---------------------------------------------------- #
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#上传路径
yuanmu:
  uploadPath: C:\workspace\booksystem/src/main/resources/upload/
  maxsize: 1024
  sufix: .jpg,.png,.gif,.jpeg